export {
  DEFAULT_VOICE_ACTIVATION_PHRASES,
  DEFAULT_VOICE_DEACTIVATION_PHRASES,
  DEFAULT_VOICE_STOP_PHRASES,
  DEFAULT_VOICE_WAKE_PHRASES,
  VOICE_STOP_COMMAND_DETAIL,
  VoiceInputClient,
  cleanupVoiceText,
  createVoiceInputDeliveryState,
  createWakeRecognitionGrammar,
  isActivationPhrase,
  isDeactivationPhrase,
  isFastActivationPartial,
  normalizeVoicePhrases,
  normalizeVoiceWakePhrases,
  prepareVoiceInputChunkForDelivery,
  trimStableVoiceTranscriptPrefix,
  type VoiceCommandPhraseGroups,
  type VoiceDeactivationMode,
  type VoiceInputAsrSocketContext,
  type VoiceInputChunk,
  type VoiceInputDeliveryState,
  type VoiceInputPhraseGroupId,
  type VoiceInputSegment,
  type VoiceInputSignalTone,
  type VoiceInputSocket,
  type VoiceInputStatus,
  type VoiceInputTransport,
} from "./web/voice-input.ts"
