import {existsSync, mkdirSync, readFileSync, writeFileSync} from "node:fs"
import {homedir} from "node:os"
import {dirname, join} from "node:path"

export const METAFOR_TMUX_CONFIG_PATH = join(homedir(), ".config", "metafor", "tmux", "metafor.tmux.conf")

const METAFOR_TMUX_PROFILE = `# MetaFor tmux profile. Generated by scripts/setup-tmux.ts.
# Keep this separate from ~/.tmux.conf so user settings stay untouched.
set -g mouse on
set -g focus-events on
set -g history-limit 50000
set -g escape-time 10
set -g repeat-time 300
set -g base-index 0
setw -g pane-base-index 0
setw -g mode-keys vi

set-environment -g -u NO_COLOR
set-environment -g -u CLICOLOR_FORCE
set-environment -g -u LC_ALL
set-environment -g COLORTERM "truecolor"
set-environment -g CLICOLOR "1"
set-environment -g FORCE_COLOR "3"
set-environment -g LANG "en_US.UTF-8"
set-environment -g LC_CTYPE "en_US.UTF-8"

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:RGB,tmux-256color:RGB,screen-256color:RGB"
set -as terminal-features ",xterm-256color:RGB,tmux-256color:RGB,screen-256color:RGB"

set -g status on
set -g status-position bottom
set -g status-interval 2
set -g status-style "bg=#08111f,fg=#94a3b8"
set -g status-left-length 72
set -g status-right-length 96
set -g status-left "#[fg=#22d3ee,bold] MetaFor #[fg=#64748b]#S #[fg=#334155]| #[fg=#e2e8f0]#W"
set -g status-right "#[fg=#64748b]%Y-%m-%d #[fg=#e2e8f0]%H:%M #[fg=#334155]| #[fg=#38bdf8]#{pane_current_command}"
set -g window-status-format " #[fg=#64748b]#I #[fg=#94a3b8]#W "
set -g window-status-current-format " #[fg=#ecfeff,bold]#I #[fg=#ecfeff,bold]#W "
set -g window-status-current-style "bg=#0e7490,fg=#ecfeff,bold"

set -g pane-border-style "fg=#334155"
set -g pane-active-border-style "fg=#22d3ee"
set -g display-panes-colour "#38bdf8"
set -g display-panes-active-colour "#facc15"
set -g message-style "bg=#0e7490,fg=#ecfeff"
set -g mode-style "bg=#155e75,fg=#ecfeff"

bind-key -T root MouseDown1Pane select-pane -t= \\; send-keys -M
bind-key -T root MouseDown2Pane select-pane -t= \\; send-keys -M
bind-key -T root MouseDown3Pane select-pane -t= \\; send-keys -M
bind-key -T root WheelUpPane select-pane -t= \\; send-keys -M
bind-key -T root WheelDownPane select-pane -t= \\; send-keys -M
`

export function ensureMetaforTmuxProfile(): {path: string; changed: boolean} {
  mkdirSync(dirname(METAFOR_TMUX_CONFIG_PATH), {recursive: true})
  const previous = existsSync(METAFOR_TMUX_CONFIG_PATH) ? readFileSync(METAFOR_TMUX_CONFIG_PATH, "utf8") : null
  if (previous !== METAFOR_TMUX_PROFILE) {
    writeFileSync(METAFOR_TMUX_CONFIG_PATH, METAFOR_TMUX_PROFILE, "utf8")
    return {path: METAFOR_TMUX_CONFIG_PATH, changed: true}
  }
  return {path: METAFOR_TMUX_CONFIG_PATH, changed: false}
}

export function metaforTmuxCommandArgs(args: string[]): string[] {
  ensureMetaforTmuxProfile()
  return ["tmux", "-f", METAFOR_TMUX_CONFIG_PATH, ...args]
}
