CREATE TABLE IF NOT EXISTS actor_value
(
    actor INTEGER NOT NULL,
    field INTEGER NOT NULL,
    value INTEGER NOT NULL,
    PRIMARY KEY (actor, field),
    FOREIGN KEY (actor) REFERENCES actor (id) ON DELETE CASCADE,
    FOREIGN KEY (field) REFERENCES field (id) ON DELETE CASCADE,
    FOREIGN KEY (value) REFERENCES value (id) ON DELETE RESTRICT
);
