CREATE TABLE IF NOT EXISTS atom_value
(
    atom INTEGER NOT NULL,
    field INTEGER NOT NULL,
    value INTEGER NOT NULL,
    PRIMARY KEY (atom, field),
    FOREIGN KEY (atom) REFERENCES atom (id) ON DELETE CASCADE,
    FOREIGN KEY (field) REFERENCES field (id) ON DELETE CASCADE,
    FOREIGN KEY (value) REFERENCES value (id) ON DELETE RESTRICT
);
