export {
  FieldType,
  applyPreparedData,
  applyWeakResultPacket,
  force,
  matrix$,
  flattenMatrixData,
  gravity$,
  listMatrixRuntimeActorIds,
  loadMatrixRuntimeSnapshot,
  prepareData,
  strong$,
  subscribeMatrixProcessTasks,
  unlock,
  update,
  write,
} from "./matrix.ts"
export type {
  MatrixDomainPath,
  MatrixForceMessage,
  MatrixProcessTask,
  MatrixProcessTaskSubscription,
  MatrixParticle,
  MatrixGravityStore,
  MatrixRuntimeSnapshot,
  PreparedData,
} from "./matrix.ts"
