#!/usr/bin/env bash
set -euo pipefail

export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=${XDG_RUNTIME_DIR}/bus}"
export WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-wayland-0}"
export XDG_SESSION_TYPE=wayland
unset DISPLAY
unset XAUTHORITY

export METAFOR_REMOTE_DESKTOP_HOST_PORT="${METAFOR_REMOTE_DESKTOP_HOST_PORT:-32133}"
export METAFOR_URL="${METAFOR_URL:-https://meta.proizvodstvo1.ru/}"
export METAFOR_REMOTE_DESKTOP_CHROME_RTC=1
export METAFOR_REMOTE_DESKTOP_MANAGED_BROWSER=1
export METAFOR_REMOTE_DESKTOP_CHROME_OZONE_PLATFORM=wayland
export METAFOR_REMOTE_DESKTOP_CHROME_USE_OZONE_FEATURE="${METAFOR_REMOTE_DESKTOP_CHROME_USE_OZONE_FEATURE:-1}"
export METAFOR_REMOTE_DESKTOP_CHROME_PIPEWIRE=1
export METAFOR_REMOTE_DESKTOP_CHROME_GPU="${METAFOR_REMOTE_DESKTOP_CHROME_GPU:-1}"
export METAFOR_REMOTE_DESKTOP_CHROME_WEBGPU="${METAFOR_REMOTE_DESKTOP_CHROME_WEBGPU:-1}"
export METAFOR_REMOTE_DESKTOP_CHROME_DEV_LAYOUT="${METAFOR_REMOTE_DESKTOP_CHROME_DEV_LAYOUT:-1}"
export METAFOR_REMOTE_DESKTOP_CHROME_DEV_MOBILE_WIDTH="${METAFOR_REMOTE_DESKTOP_CHROME_DEV_MOBILE_WIDTH:-400}"
export METAFOR_REMOTE_DESKTOP_CHROME_DEV_MOBILE_HEIGHT="${METAFOR_REMOTE_DESKTOP_CHROME_DEV_MOBILE_HEIGHT:-871}"
export METAFOR_REMOTE_DESKTOP_CHROME_DEBUG_PORT="${METAFOR_REMOTE_DESKTOP_CHROME_DEBUG_PORT:-9349}"
export METAFOR_REMOTE_DESKTOP_BROWSER_PROFILE="${METAFOR_REMOTE_DESKTOP_BROWSER_PROFILE:-/tmp/metafor-chrome-rtc-wayland-monitor-main}"
export METAFOR_REMOTE_DESKTOP_WIDTH="${METAFOR_REMOTE_DESKTOP_WIDTH:-1920}"
export METAFOR_REMOTE_DESKTOP_HEIGHT="${METAFOR_REMOTE_DESKTOP_HEIGHT:-1080}"
export METAFOR_REMOTE_DESKTOP_RTC_FPS="${METAFOR_REMOTE_DESKTOP_RTC_FPS:-60}"
export METAFOR_REMOTE_DESKTOP_RTC_VIDEO_BITRATE="${METAFOR_REMOTE_DESKTOP_RTC_VIDEO_BITRATE:-30000000}"
export METAFOR_REMOTE_DESKTOP_AUDIO="${METAFOR_REMOTE_DESKTOP_AUDIO:-1}"
export METAFOR_REMOTE_DESKTOP_CHROME_AUDIO_SOURCE="${METAFOR_REMOTE_DESKTOP_CHROME_AUDIO_SOURCE:-pipewire}"
export METAFOR_REMOTE_DESKTOP_CHROME_CAPTURE_SURFACE=monitor
export METAFOR_REMOTE_DESKTOP_CHROME_AUTO_SELECT_SOURCE="${METAFOR_REMOTE_DESKTOP_CHROME_AUTO_SELECT_SOURCE:-Entire Screen}"
export METAFOR_REMOTE_DESKTOP_CHROME_RTC_PICKER="${METAFOR_REMOTE_DESKTOP_CHROME_RTC_PICKER:-1}"
export METAFOR_REMOTE_DESKTOP_SIGNAL_URL="${METAFOR_REMOTE_DESKTOP_SIGNAL_URL:-wss://meta.proizvodstvo1.ru/hud/interpreter/webrtc/signaling}"

exec node linux-pipewire-host.cjs
