#!/usr/bin/env bash
set -euo pipefail

display="${METAFOR_XWAYLAND_DISPLAY:-:98}"
auth="${METAFOR_XWAYLAND_AUTHORITY:-/tmp/metafor-xwayland.Xauthority}"
width="${METAFOR_XWAYLAND_WIDTH:-1920}"
height="${METAFOR_XWAYLAND_HEIGHT:-1080}"

if ! DISPLAY="$display" XAUTHORITY="$auth" xdpyinfo >/dev/null 2>&1; then
  echo "Xwayland display $display is not available; start bun run xwayland:display first" >&2
  exit 1
fi

export DISPLAY="$display"
export XAUTHORITY="$auth"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-wayland-0}"
export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=${XDG_RUNTIME_DIR}/bus}"
export XDG_SESSION_TYPE="${METAFOR_XWAYLAND_SESSION_TYPE:-x11}"
export ELECTRON_ENABLE_LOGGING="${ELECTRON_ENABLE_LOGGING:-1}"
export ELECTRON_DISABLE_SANDBOX="${ELECTRON_DISABLE_SANDBOX:-1}"
export METAFOR_ELECTRON_HOST=1
export METAFOR_ELECTRON_HOST_PORT="${METAFOR_ELECTRON_HOST_PORT:-32133}"
export METAFOR_ELECTRON_DEBUG_PORT="${METAFOR_ELECTRON_DEBUG_PORT:-9240}"
export METAFOR_ELECTRON_USER_DATA_DIR="${METAFOR_ELECTRON_USER_DATA_DIR:-/tmp/metafor-electron-xwayland98-screen}"
export METAFOR_ELECTRON_OZONE_PLATFORM=x11
export METAFOR_ELECTRON_USE_OZONE_FEATURE=0
export METAFOR_ELECTRON_DISABLE_GPU="${METAFOR_ELECTRON_DISABLE_GPU:-1}"
export METAFOR_ELECTRON_VIEWPORT_WIDTH="${METAFOR_ELECTRON_VIEWPORT_WIDTH:-$width}"
export METAFOR_ELECTRON_VIEWPORT_HEIGHT="${METAFOR_ELECTRON_VIEWPORT_HEIGHT:-$height}"
export METAFOR_REMOTE_DESKTOP_RTC=1
export METAFOR_REMOTE_DESKTOP_SENDER_ONLY=1
export METAFOR_REMOTE_DESKTOP_SYSTEM_PICKER=0
export METAFOR_REMOTE_DESKTOP_CAPTURE_SOURCE="${METAFOR_REMOTE_DESKTOP_CAPTURE_SOURCE:-screen}"
export METAFOR_REMOTE_DESKTOP_CAPTURE_NAME="${METAFOR_REMOTE_DESKTOP_CAPTURE_NAME:-}"
export METAFOR_REMOTE_DESKTOP_CAPTURE_MODE="${METAFOR_REMOTE_DESKTOP_CAPTURE_MODE:-native-only}"
export METAFOR_REMOTE_DESKTOP_AUDIO="${METAFOR_REMOTE_DESKTOP_AUDIO:-1}"
export METAFOR_REMOTE_DESKTOP_AUDIO_SOURCE="${METAFOR_REMOTE_DESKTOP_AUDIO_SOURCE:-auto}"
export METAFOR_REMOTE_DESKTOP_RTC_VIDEO_BITRATE="${METAFOR_REMOTE_DESKTOP_RTC_VIDEO_BITRATE:-12000000}"
export METAFOR_REMOTE_DESKTOP_UDP_PORT_RANGE="${METAFOR_REMOTE_DESKTOP_UDP_PORT_RANGE:-40000-40100}"
export METAFOR_REMOTE_DESKTOP_PUBLIC_ICE_HOST="${METAFOR_REMOTE_DESKTOP_PUBLIC_ICE_HOST-130.49.151.168}"
export METAFOR_REMOTE_DESKTOP_ICE_INTERFACE="${METAFOR_REMOTE_DESKTOP_ICE_INTERFACE-10.66.0.10}"
export METAFOR_REMOTE_DESKTOP_IP_HANDLING_POLICY="${METAFOR_REMOTE_DESKTOP_IP_HANDLING_POLICY:-default_public_and_private_interfaces}"
export METAFOR_REMOTE_DESKTOP_SIGNAL_URL="${METAFOR_REMOTE_DESKTOP_SIGNAL_URL:-ws://10.66.0.10:6500/webrtc/signaling}"
export METAFOR_REMOTE_DESKTOP_DIRECT_INPUT_API="${METAFOR_REMOTE_DESKTOP_DIRECT_INPUT_API:-}"
export METAFOR_REMOTE_DESKTOP_FRAME_STREAM_URL="${METAFOR_REMOTE_DESKTOP_FRAME_STREAM_URL:-}"
export METAFOR_REMOTE_DESKTOP_FRAME_SNAPSHOT_URL="${METAFOR_REMOTE_DESKTOP_FRAME_SNAPSHOT_URL:-}"
export METAFOR_REMOTE_DESKTOP_AUDIO_PCM_URL="${METAFOR_REMOTE_DESKTOP_AUDIO_PCM_URL:-}"
export METAFOR_REMOTE_DESKTOP_AUDIO_URL="${METAFOR_REMOTE_DESKTOP_AUDIO_URL:-}"
export METAFOR_ELECTRON_WEBGPU=0

exec ../../node_modules/.bin/electron . \
  --ozone-platform=x11 \
  --disable-features=Vulkan,VulkanFromANGLE,VaapiVideoDecoder,VaapiVideoEncoder,WebGPU,WebRtcHideLocalIpsWithMdns \
  --disable-vulkan --enable-usermedia-screen-capturing --no-sandbox \
  --disable-gpu --disable-gpu-compositing
