export type InterpreterRouteDescription = {
  method: string
  path: string
  description: string
}

import {interpreterToolDescriptions} from "./tools.ts"

const routeIndex = [
  {method: "GET", path: "/health", description: "статус коннекта и параметры"},
  {method: "WS", path: "/ws", description: "основной websocket UI интерпретатора"},
  {method: "POST", path: "/tools", description: "единственный agent-facing command API: Codex-style {tool_uses:[{recipient_name,parameters}]}; см. tools ниже"},
  {method: "GET", path: "/tools", description: "typed registry доступных interpreter tools"},
  {method: "WS", path: "/webrtc/signaling", description: "общий локальный WebRTC signaling для shared displays: remote desktop, Android и будущие video/datachannel peers"},
  {method: "GET", path: "/webrtc/rooms", description: "diagnostics текущих WebRTC signaling rooms/peers в этом interpreter host"},
  {method: "GET", path: "/browser-display/health", description: "proxy к локальному browser-host health endpoint; требует INTERPRETER_BROWSER_HOST_URL или INTERPRETER_BROWSER_HOST_PORT"},
  {method: "GET", path: "/browser-display/state", description: "proxy к локальному browser-host state для browser-display"},
  {method: "GET", path: "/browser-display/status", description: "alias к browser-display state для UI/status controls"},
  {method: "GET", path: "/browser-display/snapshot", description: "stream proxy к локальному browser-host snapshot; сохраняет content-type/content-length"},
  {method: "POST", path: "/browser-display/navigate", description: "{url} — proxy browser-host navigate"},
  {method: "POST", path: "/browser-display/reload", description: "{ignoreCache?|hard?} — proxy browser-host reload текущей страницы"},
  {method: "POST", path: "/browser-display/back", description: "proxy browser-host navigation back"},
  {method: "POST", path: "/browser-display/forward", description: "proxy browser-host navigation forward"},
  {method: "POST", path: "/browser-display/devtools", description: "{open?|toggle?} — proxy browser-host DevTools action"},
  {method: "POST", path: "/browser-display/fullscreen", description: "{enabled?} — proxy browser-host fullscreen action"},
  {method: "POST", path: "/browser-display/viewport", description: "{width,height,deviceScaleFactor?} — proxy browser-host viewport resize"},
  {method: "POST", path: "/browser-display/input", description: "proxy browser-host input event: pointer/keyboard/wheel/focus"},
  {method: "ANY", path: "/browser-display/proxy/*", description: "safe local proxy к configured browser-host relative path; absolute/non-loopback targets запрещены"},
  {method: "GET", path: "/remote-desktop/health", description: "proxy к локальному interpreter Chrome remote desktop host health; включает WebRTC state"},
  {method: "GET", path: "/remote-desktop/state", description: "alias к remote desktop health"},
  {method: "GET", path: "/remote-desktop/status", description: "alias к remote desktop health"},
  {method: "GET", path: "/remote-desktop/lifecycle", description: "status/schema единого lifecycle API server remote desktop: user-story, параметры и текущий display/sender state"},
  {method: "POST", path: "/remote-desktop/lifecycle", description: "{action,status|start|restart|recover|stop, scope?, wait?, timeoutMs?, cleanProfile?, stopXvfb?, config?} — единая точка поднятия/перезапуска/восстановления server remote desktop"},
  {method: "GET", path: "/remote-desktop/rtc/state", description: "state WebRTC sender внутри interpreter Chrome remote desktop host"},
  {method: "POST", path: "/remote-desktop/rtc/restart", description: "перезапустить WebRTC sender/capture page interpreter Chrome host"},
  {method: "GET", path: "/remote-desktop/audio.pcm", description: "stream proxy PipeWire PCM audio для same-origin Chrome WebRTC sender"},
  {method: "GET", path: "/remote-desktop/snapshot", description: "diagnostic PNG snapshot proxy, если configured host его поддерживает; не основной realtime display"},
  {method: "POST", path: "/remote-desktop/input", description: "control input в interpreter Chrome host или configured desktop input adapter"},
  {method: "GET", path: "/remote-desktop/browser/windows", description: "remote desktop browser/window adapter diagnostics, если configured"},
  {method: "POST", path: "/remote-desktop/browser/open", description: "{url} — открыть URL в managed server Chrome или configured browser adapter"},
  {method: "GET", path: "/hud/terminal", description: "состояние host terminal HUD"},
  {method: "POST", path: "/hud/terminal/dock", description: "свернуть host terminal HUD"},
  {method: "POST", path: "/hud/terminal/show", description: "развернуть host terminal HUD"},
  {method: "POST", path: "/hud/terminal/toggle", description: "переключить host terminal HUD"},
  {method: "GET", path: "/hud/terminal/network", description: "состояние второй network terminal HUD"},
  {method: "POST", path: "/hud/terminal/network/show", description: "сфокусировать network display в Space"},
  {method: "POST", path: "/hud/terminal/network/dock", description: "оставить network tmux в Space без плавающего HUD"},
  {method: "POST", path: "/hud/terminal/network/toggle", description: "сфокусировать network display в Space"},
  {method: "GET", path: "/hud/android", description: "состояние Android HUD"},
  {method: "POST", path: "/hud/android/show", description: "развернуть Android HUD"},
  {method: "POST", path: "/hud/android/dock", description: "свернуть Android HUD"},
  {method: "POST", path: "/hud/android/toggle", description: "переключить Android HUD"},
  {method: "POST", path: "/hud/android/refresh", description: "обновить Android frame"},
  {method: "POST", path: "/hud/android/control", description: "отправить Android command через WebRTC datachannel без ADB"},
  {method: "WS", path: "/hud/android/webrtc/signaling", description: "WebRTC signaling для Android APK video/datachannel"},
  {method: "WS", path: "/hud/voice/ws", description: "единый voice WebSocket с виртуальными каналами wake/asr"},
  {method: "WS", path: "/hud/voice/wake/ws", description: "legacy public proxy к локальному voice wake/Vosk WebSocket"},
  {method: "WS", path: "/hud/voice/asr/ws", description: "legacy public proxy к локальному ASR WebSocket"},
  {method: "GET", path: "/assets/voice/models/silero_vad_16k_op15.onnx", description: "browser-side Silero VAD ONNX model для local voice activity detection"},
  {method: "GET", path: "/assets/voice/ort/ort-wasm-simd-threaded.wasm", description: "ONNX Runtime Web WASM для browser-side Silero VAD"},
  {method: "GET", path: "/android/size", description: "proxy к Android panel API: размер устройства"},
  {method: "GET", path: "/android/screencap", description: "proxy к Android panel API: текущий PNG frame"},
  {method: "POST", path: "/android/tap", description: "{x,y} — proxy Android tap"},
  {method: "POST", path: "/android/swipe", description: "{x1,y1,x2,y2,durationMs?} — proxy Android swipe"},
  {method: "POST", path: "/android/key", description: "{code} — proxy Android keyevent"},
  {method: "WS", path: "/hud/terminal/stream", description: "host PTY terminal stream"},
  {method: "GET", path: "/hud/terminal/sessions", description: "host PTY session diagnostics"},
  {method: "GET", path: "/hud/todo", description: "прочитать Plan из TODO.md и parsed items"},
  {method: "PUT", path: "/hud/todo", description: "{text} — заменить Plan в TODO.md целиком"},
  {method: "POST", path: "/hud/todo/items", description: "{text, kind?, checked?, depth?, afterId?} — добавить пункт Plan"},
  {method: "PATCH", path: "/hud/todo/items/:id", description: "{text?, checked?} — изменить текст или markdown checkbox пункта"},
  {method: "DELETE", path: "/hud/todo/items/:id", description: "удалить пункт Plan"},
  {method: "GET", path: "/hud/todo/panel", description: "состояние Plan HUD: rect/dock/highlight"},
  {method: "POST", path: "/hud/todo/highlight", description: "{id|ids|highlightedIds} — подсветить пункты в HUD для context агента"},
  {method: "POST", path: "/hud/todo/dock", description: "свернуть Plan HUD"},
  {method: "POST", path: "/hud/todo/show", description: "развернуть Plan HUD"},
  {method: "POST", path: "/hud/todo/toggle", description: "переключить Plan HUD"},
  {method: "GET", path: "/hud/sqlite", description: "состояние SQLite HUD: active database, rect/dock"},
  {method: "POST", path: "/hud/sqlite/dock", description: "свернуть SQLite HUD"},
  {method: "POST", path: "/hud/sqlite/show", description: "развернуть SQLite HUD"},
  {method: "POST", path: "/hud/sqlite/toggle", description: "переключить SQLite HUD"},
  {method: "GET", path: "/sqlite?path=<file.sqlite>&table=<name>&notBefore=<iso>", description: "просмотреть SQLite database tables/schema/rows; notBefore отсекает файл предыдущего запуска"},
  {method: "GET", path: "/sqlite/fingerprint?path=<file.sqlite>", description: "дешевый fingerprint SQLite database по main/WAL для diagnostics/server watcher; SHM только diagnostic"},
  {method: "POST", path: "/sqlite/open", description: "{path} — открыть SQLite database в HUD"},
  {method: "POST", path: "/sqlite/cell", description: "{path, table, rowid, column, value} — обновить SQLite cell по rowid"},
  {method: "POST", path: "/client-event", description: "диагностическое событие от UI-клиента; пишет компактный client.* event в event-log"},
] as const satisfies readonly InterpreterRouteDescription[]

export const interpreterTools = interpreterToolDescriptions

export const interpreterRoutes = {
  index: routeIndex,
} as const
