// Generated by dts-bundle-generator v9.5.1

/**
 * Результат парсинга атрибута.
 */
export type ParseAttributeResult = {
	/** Путь(и) к данным (необязательное) */
	data?: string | string[];
	/** Унифицированное выражение (необязательное) */
	expr?: string;
	/** Ключи для обновления (необязательное) */
	upd?: string | string[];
};
export type Context = Record<string, string | number | boolean | null | Array<string | number | boolean | null>>;
export type Core = Record<string, any>;
export type State = string;
export type RenderParams<C extends Context, I extends Core = Core, S extends State = State> = {
	html: (strings: TemplateStringsArray, ...values: any[]) => string;
	core: I;
	context: C;
	state: State;
	update: (context: Partial<C>) => void;
};
/**
 * Узел HTML элемента.
 * Представляет HTML тег с атрибутами и дочерними элементами.
 */
export interface NodeElement extends AttributesNode {
	/** Имя HTML тега */
	tag: string;
	/** Тип узла - всегда "el" для элементов */
	type: "el";
	/** Дочерние узлы элемента */
	child?: Node[];
}
/**
 * Текстовый узел.
 * Представляет текст с путями к данным или статическими значениями.
 */
export interface NodeText {
	/** Тип узла - всегда "text" для текстовых узлов */
	type: "text";
	/** Путь(и) к данным (если текст динамический) */
	data?: string | string[];
	/** Статическое значение (если текст статический) */
	value?: string;
	/** Выражение с индексами (если текст смешанный) */
	expr?: string;
}
/**
 * Узел map операции.
 * Представляет итерацию по массиву данных с дочерними элементами.
 */
export interface NodeMap {
	/** Тип узла - всегда "map" для map операций */
	type: "map";
	/** Путь к массиву данных для итерации */
	data: string;
	/** Дочерние узлы, которые будут повторены для каждого элемента массива */
	child: Node[];
}
/**
 * Узел условного оператора.
 * Представляет тернарный оператор с ветками true и false.
 */
export interface NodeCondition {
	/** Тип узла - всегда "cond" для условных операторов */
	type: "cond";
	/** Путь(и) к данным для условия */
	data: string | string[];
	/** Выражение с индексами (если условие сложное) */
	expr?: string;
	/** Узел для случая когда условие истинно */
	true: Node;
	/** Узел для случая когда условие ложно */
	false: Node;
}
/**
 * Мета-узел.
 * Представляет мета-тег с динамическим именем тега.
 */
export interface NodeMeta extends AttributesNode {
	/** Имя мета-тега (может быть динамическим) */
	tag: string | ParseAttributeResult;
	/** Тип узла - всегда "meta" для мета-узлов */
	type: "meta";
	/** Дочерние элементы (опционально) */
	child?: Node[];
}
export interface AttributesNode {
	/** События */
	event?: AttributeEvent;
	/** Булевые аттрибуты */
	boolean?: AttributeBoolean;
	/** Массивы аттрибутов */
	array?: AttributeArray;
	/** Строковые аттрибуты */
	string?: AttributeString;
	/** Объектные аттрибуты (стили) */
	object?: AttributeObject;
}
export type AttrVariable = {
	data: string;
};
export type AttrDynamic = {
	data: string | string[];
	expr: string;
};
export type AttrUpdate = {
	data?: string | string[];
	expr?: string;
	upd: string | string[];
};
export type AttributeEvent = Record<string, AttrVariable | AttrDynamic | AttrUpdate | {
	expr: string;
	upd?: string | string[];
}>;
export type AttributeArray = Record<string, (AttrStaticArray | AttrVariable | AttrDynamic)[]>;
export type AttrStaticArray = {
	value: string;
};
export type AttributeString = Record<string, AttrStaticString | AttrVariable | AttrDynamic>;
export type AttrStaticString = string;
export type AttributeBoolean = Record<string, boolean | AttrVariable | AttrDynamic>;
export type AttributeObject = Record<string, Record<string, string>>;
export type Node = NodeMap | NodeCondition | NodeText | NodeElement | NodeMeta;
/**
 * Парсит HTML-шаблон и возвращает обогащенную иерархию с метаданными о путях к данным.
 *
 * Эта функция является основным публичным API парсера. Она принимает render-функцию
 * и выполняет полный цикл обработки:
 * 1. Извлекает основной HTML блок из template literal
 * 2. Разбивает HTML на токены элементов
 * 3. Строит иерархию элементов с поддержкой map и условий
 * 4. Обогащает иерархию метаданными о путях к данным, выражениях и статических значениях
 *
 * Поддерживает все возможности парсера:
 * - HTML элементы с атрибутами
 * - Template literals с переменными ${...}
 * - Map операции для итерации по коллекциям
 * - Условные операторы (тернарные)
 * - Вложенные структуры любой сложности
 * - События и динамические атрибуты
 * - Web Components
 *
 * @param render - Render-функция вида ({ html, context, core, state }) => html`...`
 * @returns Обогащенная иерархия с метаданными о путях к данным
 *
 * @example
 * ```typescript
 * // Простой HTML с переменными
 * const result = parse(({ html, context }) => html`
 *   <div class="${context.userStatus}">
 *     <h1>Hello ${context.userName}!</h1>
 *     <p>You have ${context.messageCount} messages</p>
 *   </div>
 * `)
 *
 * // HTML с map операциями
 * const result = parse(({ html, context }) => html`
 *   <ul>
 *     ${context.users.map((user) => html`
 *       <li class="${user.active ? 'active' : 'inactive'}">
 *         ${user.name} - ${user.email}
 *       </li>
 *     `)}
 *   </ul>
 * `)
 *
 * // HTML с условиями
 * const result = parse(({ html, context }) => html`
 *   <div>
 *     ${context.isAdmin ? html`
 *       <button onclick="${() => context.adminPanel.open()}">Admin Panel</button>
 *     ` : html`
 *       <span>Access denied</span>
 *     `}
 *   </div>
 * `)
 * ```
 */
export declare const parse: <C extends Context, I extends Core, S extends State>(render: (params: RenderParams<C, I, S>) => void) => Node[];

export {};
