import "@metafor/meta"

export default MetaFor("git-plumbing").context((t) => ({
  command: t.enum(
    "cat-file",
    "check-attr",
    "check-ignore",
    "check-mailmap",
    "commit-graph",
    "commit-tree",
    "count-objects",
    "diff-files",
    "diff-index",
    "diff-tree",
    "fast-export",
    "fast-import",
    "filter-branch",
    "fsck",
    "gitfile",
    "hash-object",
    "mktree",
    "multi-pack-index",
    "prune",
    "reflog",
    "rev-list",
    "rev-parse",
    "show-ref",
    "symbolic-ref",
    "unpack-objects",
    "update-index",
    "update-ref",
    "verify-commit",
    "verify-pack",
    "verify-tag"
  ).optional({ label: "Низкоуровневые команды (plumbing)" }),
}))
