<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 ./static/bots.glb
-->

<script>
  import { Group } from "three"
  import { T, forwardEventHandlers } from "@threlte/core"
  import { useGltf, useGltfAnimations } from "@threlte/extras"
  import bots from "$lib/bots.glb?url"
  export const ref = new Group()

  const gltf = useGltf(bots)
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
  $: Object.entries($actions).forEach(([key, value]) => {
    console.log(key, value)
    value?.play()
  })
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature001" position={[0, 0, 0.59]} rotation={[Math.PI / 2, 0, 3.11]} scale={0.01}>
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="Beta_Joints"
          geometry={gltf.nodes.Beta_Joints.geometry}
          material={gltf.materials.Beta_Joints_MAT1}
          skeleton={gltf.nodes.Beta_Joints.skeleton}
        />
        <T.SkinnedMesh
          name="Beta_Surface"
          geometry={gltf.nodes.Beta_Surface.geometry}
          material={gltf.materials.Beta_HighLimbsGeoSG3}
          skeleton={gltf.nodes.Beta_Surface.skeleton}
        />
      </T.Group>
      <T.Group name="Armature" position={[0, 0, -0.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <T is={gltf.nodes.mixamorigHips_1} />
        <T.SkinnedMesh
          name="Alpha_Joints"
          geometry={gltf.nodes.Alpha_Joints.geometry}
          material={gltf.materials["Alpha_Joints_MAT.001"]}
          skeleton={gltf.nodes.Alpha_Joints.skeleton}
        />
        <T.SkinnedMesh
          name="Alpha_Surface"
          geometry={gltf.nodes.Alpha_Surface.geometry}
          material={gltf.materials["Alpha_Body_MAT.001"]}
          skeleton={gltf.nodes.Alpha_Surface.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
